#!/usr/bin/env bash
# shellcheck source=scripts/setup-python

set -e

python3 -m venv .venv
.venv/bin/python -m pip install --upgrade pip
# See: pip and pip-tools bug https://github.com/jazzband/pip-tools/issues/1617
.venv/bin/python -m pip install pip-tools
.venv/bin/pip-sync

echo "Python setup complete"
